### ISSUE TITLE
ZIP64 Errors

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-compress-commons#33]
from https://github.com/archiverjs/node-archiver/issues/325

**Comment by JasonWoof** [comment]
I found what looks like a mismatch between the spec and the code, and I think it might be what's causing this bug.

reading here: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

it says: "When extracting, if the zip64 extended information extra field is present for the file the compressed and uncompressed sizes will be 8 byte values."

But in the code in this repo there's a different check for whether to add the extra field vs check if the sizes should be 8 bytes:

https://github.com/archiverjs/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-output-stream.js#L271

in: ZipArchiveOutputStream.prototype._writeCentralFileHeader = function(ae) {

line: if (ae.isZip64() || offsets.file > constants.ZIP64_MAGIC) {

vs

https://github.com/archiverjs/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-output-stream.js#L355

in: ZipArchiveOutputStream.prototype._writeDataDescriptor = function(ae) {

line: if (ae.isZip64()) {


So if I'm reading this right, if you're 4GiB or more (offset) into the file, and you put a small (less than 4GiB) file into the archive, it'll be corrupted because it'll get the zip64 header, but get 4-byte size fields in the data descriptor.

**Comment by ctalkington** [comment]
ref https://github.com/archiverjs/node-archiver/issues/371

**Comment by ctalkington** [comment]
maybe https://github.com/archiverjs/node-archiver/issues/602

**Comment by ctalkington** [comment]
https://github.com/archiverjs/node-compress-commons/pull/171 seems like it may resolve this
